# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
   os: "ubuntu-22.04"
   tools:
      python: "3.10"
   jobs:
      post_create_environment:
         # Install poetry
         # https://python-poetry.org/docs/#installing-manually
         - pip install poetry
         # Tell poetry to not use a virtual environment
         - poetry config virtualenvs.create false
         - poetry install --only main
         # Extremely weird bug with the wheels of pydata-sphinx-theme if we use poetry,
         # so resorting to exporting the environment and installing with pip.
         - poetry export --format=requirements.txt --only docs > requirements.txt
         - pip install -r requirements.txt
